//APP
export const RESET = 'APP_RESET';
export const APP_REQUEST_SUCCESS = 'APP_REQUEST_SUCCESS';
export const APP_POSTING_REQUEST = 'APP_POSTING_REQUEST';

//FormUtil
export const SET_TEXT = 'SET_TEXT';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const POSTING_REQUEST = 'POSTING_REQUEST';
export const RESPONSE_RECEIVED = 'RESPONSE_RECEIVED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ERROR = 'ERROR';

export const LOGIN_POSTING_REQUEST = 'LOGIN_POSTING_REQUEST';
export const LOGIN_RESPONSE_RECEIVED = 'LOGIN_RESPONSE_RECEIVED';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
